import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Usecartcontext from '@/components/Usecartcontext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Ponno-bazar',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen flex-col`}>
    <Usecartcontext>
        <Header></Header>

         <main className=" flex-1 ">{children}</main>
        <Footer></Footer>
    </Usecartcontext>

 
      </body>
    </html>
  );
}
